### ISSUE TITLE
gossip: export new inbound fee related gauges

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lndmon#107]
With the release of lnd v0.18.0 we have a new piece of data to export/graph/analyze: inbound fee discounts. 

We should export two new gauges so we can track the uptake of this new feature on the network:
   * A gauge for the total amount of channel updates that set the inbound fee to a non-zero value. 
      * We can also check the code check for existence of the new TLV as well, so even those that have upgraded, but set it to zero would contribute to this metric. 
   * A histogram for the various values of the inbound fee discount. We can use this to create percentile graphs and heatmaps, etc.

**Comment by levmi** [comment]
It would also be cool to add this to rankings down the line in some way potentially cc @bitromortac @jbrill @dstrukt
