### ISSUE TITLE
[Feature Request] Graceful reconnect to lnd

### ISSUE THREAD

**Issue by cfromknecht** [lightninglabs/lndmon#34]
If lnd is restarted while lndmon is running, lndmon will fail to connect back to lnd and continue grabbing metrics. The result is that the gap in the metrics ends up much larger than the actual downtime of lnd until lndmon is restarted entirely.

**Comment by carlaKC** [comment]
#58 updated lndmon to exit if it gets an error from lnd. If you're running using the the compose setup, lndmon should just cycle and reconnect now ✨
