### ISSUE TITLE
Set "monitoring tag" for LND Docker builds

### ISSUE THREAD

**Issue by lispmeister** [lightninglabs/lndmon#69]
Customers requested this to be switched on by default for container images we publish (according to Ryan).Build lnd with the build tag monitoring.
From the docs:

> Utilizing the monitoring build tag requires building lnd from source. To build lnd from source, follow the instructions here except instead of running `make && make install, run make && make install tags=monitoring`.

**Comment by szollo** [comment]
It might make sense to have this as a conditional if a specific env var is set, rather than necessarily a default.

We currently use the flag on our own Dockerfile at Zap (https://github.com/LN-Zap/docker-lnd/blob/master/Dockerfile#L21), in order to allow us to use lndmon.
