### ISSUE TITLE
Health checks randomly take too long

### ISSUE THREAD

**Issue by krtk6160** [lightninglabs/lndmon#71]
We are running lndmon inside a kubernetes pod and are experiencing strange behavior with the `/health` endpoint. Our liveness and/or readiness probes start failing randomly with timeout errors. We were having ~3 incidents per day but now it's close to ~30 per day.

We are using a timeout of `20s` which should be more than enough for the health check.

**Comment by Roasbeef** [comment]
Which endpoint are you referring to?

**Comment by krtk6160** [comment]
> Which endpoint are you referring to?

Like mentioned above, the `/health` endpoint. The one that returns:
`{"status":200,"message":"Successfully connected to LND RPC"}` on success

**Comment by Roasbeef** [comment]
Can you link to this endpoint in the codebase? Are you using a _fork_ of `lndmon` perhaps?

**Comment by krtk6160** [comment]
Ah yes, I cannot find it in the codebase. I found radar tech's lndmon docker image [here](https://hub.docker.com/r/radarion/lndmon) and since LL does not host lndmon docker images on dockerhub yet, I just decided to use this.
It seems like it's been modified.

My apologies.
