### ISSUE TITLE
Where are releases published?

### ISSUE THREAD

**Issue by bodymindarts** [lightninglabs/lndmon#72]
The latest release visible in this repo is from 2019 https://github.com/lightninglabs/lndmon/releases/tag/v0.1.0.
Is this compatible with latest lnd? There have been many commits since then - is there a place where the latest official image (that is known to work with current lnd) is published? Is there a way to be notified when there is a newer release?

**Comment by carlaKC** [comment]
The latest release can be found here: https://github.com/lightninglabs/lndmon/releases/tag/v0.2.0. 

Looks like github flattens the tags if they don't have a full release doc associated with them. Next time we'll be sure to create a release doc with changelog etc. 
![Screenshot 2021-07-29 at 09 21 47](https://user-images.githubusercontent.com/42311294/127449282-08d6f54a-9545-48cb-aeaa-a544245d7620.png)

>  Is there a way to be notified when there is a newer release?

Subscribing to github notifications should keep you in the loop, and we announce releases on [twitter](https://twitter.com/lightning) and the [LL blog](https://lightning.engineering/blog). 

>  is there a place where the latest official image

We don't have official images for lndmon yet, but you can build it using the Dockerfile that's checked in for the repo. The current version works with lnd 0.13.1.

**Comment by bodymindarts** [comment]
Thx
