### ISSUE TITLE
error subscribing to lnd wallet state: lnd version incompatible

### ISSUE THREAD

**Issue by audleman** [lightninglabs/lndmon#82]
I'm getting the following error
```
error subscribing to lnd wallet state: lnd version incompatible, need at least v0.13.0-beta, got error on state subscription: rpc error: code = Unavailable desc = connection closed
```

My lightning version is newer than the version listed
```
lnd_1         | 2022-07-21 17:56:19.450 [INF] LTND: Version: 0.15.0-beta commit=v0.15.0-beta-141-gd9f4b36cb, build=production, logging=default, debuglevel=info
lnd_1         | 2022-07-21 17:56:19.450 [INF] LTND: Active chain: Bitcoin (network=mainnet)
```

I tried rolling back to v0.13.0-beta explicitly and still got the error. 

Any ideas on what the problem is?

**Comment by guggero** [comment]
Yes, this is because we need to update the `lndclient` version that `lndmon` uses to be forward compatible. It's a pretty simple change, I'll try to get a PR up soon.
