### ISSUE TITLE
Lndmon exiting with error: WalletCollector ListUnspent failed with: invalid utxo address type 4

### ISSUE THREAD

**Issue by kiwiidb** [lightninglabs/lndmon#87]
After upgrading to LND 0.15.1, lndmon crashes with this error.

```
2022-09-11 08:33:29.979 [INF] LNDMON: Starting Prometheus exporter...
2022-09-11 08:33:29.980 [INF] HTLC: Starting Htlc Monitor
2022-09-11 08:33:29.980 [INF] LNDMON: Prometheus active!
Lndmon exiting with error: WalletCollector ListUnspent failed with: invalid utxo address type 4
2022/09/11 08:33:34 Stopping Prometheus Exporter
2022-09-11 08:33:34.429 [INF] HTLC: Stopping Htlc Monitor
WalletCollector ListUnspent failed with: invalid utxo address type 4
```

**Comment by kiwiidb** [comment]
I suspect this will probably be solved by using a release with the most up-to-dat LND dependencies, I see there was a commit last month, will try and build from master to see if that does the trick.

**Comment by guggero** [comment]
I think all you need to do is bump `lndclient` to `v0.15.0-15`.

**Comment by Roasbeef** [comment]
Tried bumping, and it didn't resolve the issue, investigating further.

**Comment by Roasbeef** [comment]
AFAICT, lndclient needs to be updated too: https://github.com/lightninglabs/lndclient/blob/lnd-16-0/walletkit_client.go#L225-L238
