### ISSUE TITLE
Docker images on DockerHub are not up to date

### ISSUE THREAD

**Issue by rsafier** [lightninglabs/lndmon#89]
Would be convenient if latest release was offer on dockerhub: https://hub.docker.com/r/lightninglabs/lndmon/tags
looks like last version was 2 months ago.

**Comment by guggero** [comment]
There wasn't a new tag pushed since August 2, so no new builds are created either. I guess you're asking for us to bundle a new version with the recent changes?

**Comment by rsafier** [comment]
yes would make it much easier for us to deploy into production, otherwise we will need to cut our own image

**Comment by guggero** [comment]
Okay, I pushed a new tag `v0.2.2`, the docker image for it should be available on Docker Hub in a few minutes (see https://github.com/lightninglabs/lndmon/actions/runs/3228962180 for status).
